# Mosquitto config for local AmpereX development
# Anonymous access is fine for a hackathon on localhost/local network.
# Do NOT use allow_anonymous true if you ever expose this broker publicly.

listener 1883
allow_anonymous true

persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
